name: GraphQL Inspector
on:
  pull_request:
    branches: [ main ]
jobs:
  test:
    name: Check Schema
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: kamilkisiela/graphql-inspector@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          schema: 'main:schema.graphql'
          fail-on-breaking: false

